cache:
	deno cache -c deno.json --unstable ./src/kindelia.ts

cache-reload:
	deno cache -c deno.json --unstable --reload ./src/kindelia.ts

fmt:
	deno fmt -c deno.json ./src/

lint:
	deno lint -c deno.json --unstable ./src/
